"""garden model now back to user id instead of owner id

Revision ID: 9e63b5449059
Revises: e379f9994631
Create Date: 2023-06-08 10:49:12.101629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e63b5449059'
down_revision = 'e379f9994631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('garden_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('garden_ibfk_1', 'user', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
